# Get all users
GET http://localhost:3003/users
Content-Type: application/json

###

# Add new user
POST http://localhost:3003/users
Content-Type: application/json

{
    "name":"Jonas",
    "cpf": 234567891231,
    "birthdate": "2003/11/08"
}

###

# Get user balance
GET http://localhost:3003/user/balance?cpf=23456789123
Content-Type: application/json

###

# Deposit into user's account
PUT http://localhost:3003/user
Content-Type: application/json

{
    "name":"Maria",
    "cpf":12345678901,
    "amount": 1000
}

###

# Add a transaction to a user history
PUT http://localhost:3003/user/pay
Content-Type: application/json

{
    "date": "2022-11-10",
    "description": "Credit Card",
    "amount": 1000, 
    "cpf":12345678901
}

###

# Update user balance according to it's transactions
PUT http://localhost:3003/user/update-balance
Content-Type: application/json

{
    "cpf":23456789123
}