GET http://localhost:3003/users
Content-Type: application/json

###

POST http://localhost:3003/users
Content-Type: application/json

{
    "name":"Jonas",
    "cpf": 23456789123,
    "birthdate": "2003/11/08"
}

###

GET http://localhost:3003/user/balance?cpf=23456789123
Content-Type: application/json